# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  # aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  # To use cloudinary in dev, get url with:
  # heroku config:get CLOUDINARY_URL
  # and export it to your local env with:
  # export CLOUDINARY_URL=cloudinary://.......
  # check it with:
  # printenv
  secret_key_base: 20dbf7add3eb28096f1e77cb4e15f13a46e6692f4d0c0f9a3e9db7cb4ddaa8a7cac0912cc1f8ac9ae1fae9eb3115e2dbd32b1e626ca72da9c9fc83beb2cb6312
  cloudinary_url: <%= ENV['CLOUDINARY_URL'] %>
test:
  # aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  # aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  secret_key_base: a412eca4343e70b5e50093bf6935bfc4c68f1381a6d0e73b5ef262bc569da6cf022552764a4fb118e0b92b7285550bf55f32cfc18a5be36810ec5caf5d6929c3
  cloudinary_url: <%= ENV['CLOUDINARY_URL'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  # aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_url: <%= ENV['CLOUDINARY_URL'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
# for heroku set these values like so:
# heroku config:set AWS_ACCESS_KEY_ID='your aws_access_key_id'
# heroku config:set AWS_SECRET_ACCESS_KEY='your aws_secret_access_key'

# for local dev set these values like so:
# export AWS_ACCESS_KEY_ID='your aws_access_key_id'
# export AWS_SECRET_ACCESS_KEY='your aws_secret_access_key'

precompile:
  secret_key_base: 20dbf7add3eb28096f1e77cb4e15f13a46e6692f4d0c0f9a3e9db7cb4ddaa8a7cac0912cc1f8ac9ae1fae9eb3115e2dbd32b1e626ca72da9c9fc83beb2cb6312
